Uncertainty estimation, calibration/sharpness, post-processing calibration
stanfordmlgroup/methane-gapfill-ml pull request #6
Opened 2021-07-21 05:01 UTC by jirvin16

**Problem**

We need to produce and evaluate uncertainty estimates around the CH4 predictions.

**Solution**

Implement uncertainty estimation using Laplace and Normal distributions, calibration/sharpness metrics, and post-processing calibration (uncertainty scaling).

**Tests**

```
python main.py test --sites MPM --models lasso,rf --predictors_paths predictors/mpm_predictors.txt --overwrite_results
python main.py test --sites NZKop --models lasso,rf --predictors_paths predictors/all.txt --overwrite_results
```

2021-07-26 04:02 UTC, ylzhouchris commented
**Problem**
Values of scaled sharpness (normalized or not) are too large (*10^8). Please see if this is expected. Maybe double check the implemented Platt scaling. 

Another optional minor is that it would be better to put all results together. The new pull request adds a "results" folder in the root directory. Results are stored in a "test.csv" which can be confusing to outputs from previous steps.

2021-07-26 04:05 UTC, ylzhouchris requested changes

2021-07-26 04:05 UTC, ylzhouchris commented on models/ensemble.py
> +            raise ValueError(f"Distribution {distribution} not supported.")
Please double-confirm the implemented scaling of the distributions. It's leading to exceedingly large widths.mean() outputs.

2021-07-29 08:03 UTC, jirvin16 commented
> **Problem**
> Values of scaled sharpness (normalized or not) are too large (*10^8). Please see if this is expected. Maybe double check the implemented Platt scaling.
> 
> Another optional minor is that it would be better to put all results together. The new pull request adds a "results" folder in the root directory. Results are stored in a "test.csv" which can be confusing to outputs from previous steps.

You were absolutely right re: large sharpness! There was a bug with the Laplace implementation that led to exponentiated values. That's been fixed and the sharpness values look much more reasonable. Nice catch.

Thanks for raising the results issue too. I've tried to clean this up by writing results for each model to the corresponding model directory, and writing all aggregated results to `results/` - let me know what you think.

2021-07-31 13:46 UTC, ylzhouchris commented
Hi Jeremy, thanks for the revisions made! I think the pull request can be approved.

2021-07-31 13:46 UTC, ylzhouchris approved these changes

2021-07-31 13:48 UTC, merged